# Generated by Django 5.2.1 on 2025-05-13 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_delete_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(default='bio', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
